#!/usr/bin/env bash
#
# adapt.sh — Generate tool-specific config files from CLAUDE.md
#
# Usage: bash scripts/adapt.sh <tool>
#   tool: cursor | windsurf | cline | codex
#
# Reads CLAUDE.md from the current directory, inlines all @import references,
# and outputs to the correct filename for the target tool.

set -euo pipefail

# --- Help ---
if [[ $# -eq 0 ]]; then
  cat <<'HELP'
Loci Adapt — Generate config files for other AI coding tools

Usage:
  bash scripts/adapt.sh <tool>

Tools:
  cursor    → .cursorrules
  windsurf  → .windsurfrules
  cline     → .clinerules
  codex     → AGENTS.md (read-only mode, no slash commands or persistence)

Examples:
  bash scripts/adapt.sh cursor
  bash scripts/adapt.sh codex

Run from your Loci brain root directory (where CLAUDE.md lives).
HELP
  exit 0
fi

TOOL="$1"
BRAIN_DIR="$(pwd)"
SOURCE="$BRAIN_DIR/CLAUDE.md"

# --- Validate ---
if [[ ! -f "$SOURCE" ]]; then
  echo "Error: CLAUDE.md not found in current directory."
  echo "Run this script from your Loci brain root directory."
  exit 1
fi

# --- Determine output file ---
case "$TOOL" in
  cursor)   OUTPUT=".cursorrules" ;;
  windsurf) OUTPUT=".windsurfrules" ;;
  cline)    OUTPUT=".clinerules" ;;
  codex)    OUTPUT="AGENTS.md" ;;
  *)
    echo "Error: Unknown tool '$TOOL'"
    echo "Supported: cursor, windsurf, cline, codex"
    exit 1
    ;;
esac

# --- Inline @import references ---
# Reads CLAUDE.md line by line. When a line matches @<path>, replaces it
# with the file contents. Otherwise passes the line through.
inline_imports() {
  local file="$1"
  while IFS= read -r line; do
    # Match lines like: @plan.md or @docs/behavior.md (with optional leading whitespace)
    if [[ "$line" =~ ^[[:space:]]*@([a-zA-Z0-9_./-]+\.md)[[:space:]]*$ ]]; then
      local import_path="${BASH_REMATCH[1]}"
      local full_path="$BRAIN_DIR/$import_path"
      if [[ -f "$full_path" ]]; then
        echo ""
        echo "<!-- Inlined from $import_path -->"
        cat "$full_path"
        echo ""
        echo "<!-- End $import_path -->"
      else
        echo ""
        echo "<!-- WARNING: $import_path not found, skipped -->"
      fi
    else
      echo "$line"
    fi
  done < "$file"
}

# --- Build output ---
CONTENT="$(inline_imports "$SOURCE")"

# --- Add header ---
HEADER="# Generated by Loci adapt.sh for $TOOL
# Source: CLAUDE.md (with imports inlined)
# Date: $(date '+%Y-%m-%d %H:%M')
# Regenerate: bash scripts/adapt.sh $TOOL
#
# Do not edit this file directly — edit CLAUDE.md and re-run adapt.sh.
"

# --- Codex-specific: strip slash commands and persistence logic ---
if [[ "$TOOL" == "codex" ]]; then
  # Remove slash command references (/loci-sync, /loci-link, /loci-settings, etc.)
  # Remove the Persistence (Synapse) section
  # Add a read-only note
  CODEX_NOTE="
> **Codex Compatibility Note**: This file was adapted for OpenAI Codex (read-only mode).
> Slash commands are not available in this mode.
> Persistence/Synapse auto-save is disabled — memory files are read-only reference.
> To update your brain, use Claude Code or edit files manually.
"

  CONTENT=$(echo "$CONTENT" | awk '
    BEGIN { skip=0 }
    # Skip the Persistence (Synapse) section until next ## heading
    /^## Persistence \(Synapse\)/ { skip=1; next }
    /^### \/loci-sync/ { skip=1; next }
    /^### Auto mode/ { skip=1; next }
    /^### Manual mode/ { skip=1; next }
    skip==1 && /^## / { skip=0 }
    skip==1 { next }
    # Remove lines that are just slash command references
    /^\/loci-sync/ { next }
    /^\/loci-link/ { next }
    /^\/loci-settings/ { next }
    /^\/loci-brain-settings/ { next }
    /^\/loci-scan/ { next }
    # Remove backtick-wrapped slash commands in running text
    { gsub(/`\/loci-sync[^`]*`/, "(manual edit)") }
    { gsub(/`\/loci-link[^`]*`/, "(manual link)") }
    { gsub(/`\/loci-settings[^`]*`/, "(manual config)") }
    { gsub(/\/loci-sync/, "(manual edit)") }
    { gsub(/\/loci-link/, "(manual link)") }
    { gsub(/\/loci-settings/, "(manual config)") }
    { print }
  ')

  CONTENT="${CODEX_NOTE}
${CONTENT}"
fi

# --- Write output ---
echo "${HEADER}
${CONTENT}" > "$BRAIN_DIR/$OUTPUT"

# --- Summary ---
LINES=$(wc -l < "$BRAIN_DIR/$OUTPUT" | tr -d ' ')
SIZE=$(wc -c < "$BRAIN_DIR/$OUTPUT" | tr -d ' ')

echo "Loci adapt: Generated $OUTPUT for $TOOL"
echo "  Source:  CLAUDE.md (imports inlined)"
echo "  Output:  $OUTPUT ($LINES lines, ${SIZE} bytes)"
if [[ "$TOOL" == "codex" ]]; then
  echo "  Mode:    Read-only (slash commands and persistence stripped)"
fi
echo ""
echo "Add $OUTPUT to .gitignore — it's a generated file."
